version: '3'

services:
  app:
    build: .
    tty: true
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8000"
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64 # for Apple M1 chip
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: upload
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

volumes:
  db_data: {}
